baseURL = 'https://blog.mo0.jp/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'ã©ã‚‰ã‚‚æ—¥è¨˜'
theme = "PaperMod"
description = 'æ±äº¬ â†’ å¤§é˜ª 19æ­³ã®æ—¥è¨˜ã£ã½ã„æŠ€è¡“ãƒ–ãƒ­ã‚°'

[params]

    [params.author]
        name = "R.U"
    
    [params.assets]
        favicon = "images/favicon.ico"
        # apple_touch_icon = "apple-touch-icon.png"
        # safari_pinned_tab = "safari-pinned-tab.svg"
    
    #"regular"ï¼ˆé€šå¸¸ï¼‰| "home-info"ï¼ˆè‡ªå·±ç´¹ä»‹è¡¨ç¤ºï¼‰| "profile"ï¼ˆãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«ä¸­å¿ƒï¼‰
    # homeInfoMode = "home-info"
    
    mainSections = ["page/posts/"]

    [params.homeInfoParams]
        Title = "R.U ğŸ².ğŸ„"
        Content = "18æ­³ã§æ±äº¬ã‹ã‚‰å¤§é˜ªã«ç§»ä½ã—ãŸç‹¬å­¦Cè¨€èªã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢"
        AlignSocialIconsTo = "left"
    
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/rmo0"
            
    DateFormat = ":date_long"
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCruãƒ¼ãƒ¼bs = true
    ShowCodeCopyButtons = true
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true

    [params.cover]
        hidden = false
        hiddenInList = false
    
    [params.search]
        Enable = true
    
    [params.shareicons]
        enable = true